const OK_STATUS_CODE = 200;
const CREATED_STATUS_CODE = 201;
const UPDATED_STATUS_CODE = 204;
const BAD_REQUEST_STATUS_CODE = 400;
const UNAUTHORIZED_STATUS_CODE = 401;
const NOT_AUTHORIZED_STATUS_CODE = 403;
const NOT_FOUND_STATUS_CODE = 404;
const DUPLICATE_CONFLICT_STATUS_CODE = 409;
const INTERNAL_SERVER_ERROR_STATUS_CODE = 500;

module.exports = {
  OK_STATUS_CODE,
  CREATED_STATUS_CODE,
  UPDATED_STATUS_CODE,
  BAD_REQUEST_STATUS_CODE,
  UNAUTHORIZED_STATUS_CODE,
  NOT_AUTHORIZED_STATUS_CODE,
  NOT_FOUND_STATUS_CODE,
  DUPLICATE_CONFLICT_STATUS_CODE,
  INTERNAL_SERVER_ERROR_STATUS_CODE,
};
